export const REPO_RESET_STATE = 'REPO_RESET_STATE';
export const REPO_REQUEST_LOADING = 'REPO_REQUEST_LOADING';
export const REPO_REQUEST_LOADING_SUCCESS = 'REPO_REQUEST_LOADING_SUCCESS';
export const REPO_REQUEST_LOADING_FAILURE = 'REPO_REQUEST_LOADING_FAILURE';

export const LIST_ALL_REPO_REQUEST_LOADING = 'LIST_ALL_REPO_REQUEST_LOADING';
export const LIST_ALL_REPO_REQUEST_LOADING_SUCCESS = 'LIST_ALL_REPO_REQUEST_LOADING_SUCCESS';
export const LIST_ALL_REPO_REQUEST_LOADING_FAILURE = 'LIST_ALL_REPO_REQUEST_LOADING_FAILURE';

export const REPO_ADD_NEW_REPO_REQUEST_LOADING = 'REPO_ADD_NEW_REPO_REQUEST_LOADING';
export const REPO_ADD_NEW_REPO_REQUEST_LOADING_SUCCESS = 'REPO_ADD_NEW_REPO_REQUEST_LOADING_SUCCESS';
export const REPO_ADD_NEW_REPO_REQUEST_LOADING_FAILURE = 'REPO_ADD_NEW_REPO_REQUEST_LOADING_FAILURE';

export const REPO_EDIT_REPO_REQUEST_LOADING = 'REPO_EDIT_REPO_REQUEST_LOADING';
export const REPO_EDIT_REPO_REQUEST_LOADING_SUCCESS = 'REPO_EDIT_REPO_REQUEST_LOADING_SUCCESS';
export const REPO_EDIT_REPO_REQUEST_LOADING_FAILURE = 'REPO_EDIT_REPO_REQUEST_LOADING_FAILURE';

export const REPO_LIST_CARD_ADD_NEW_LOADING = 'REPO_LIST_CARD_ADD_NEW_LOADING';
export const REPO_LIST_CARD_ADD_NEW_LOADING_SUCCESS = 'REPO_LIST_CARD_ADD_NEW_LOADING_SUCCESS';
export const REPO_LIST_CARD_ADD_NEW_LOADING_FAILURE = 'REPO_LIST_CARD_ADD_NEW_LOADING_FAILURE';

export const REPO_LIST_CARD_EDIT_LOADING = 'REPO_LIST_CARD_EDIT_LOADING';
export const REPO_LIST_CARD_EDIT_LOADING_SUCCESS = 'REPO_LIST_CARD_EDIT_LOADING_SUCCESS';
export const REPO_LIST_CARD_EDIT_LOADING_FAILURE = 'REPO_LIST_CARD_EDIT_LOADING_FAILURE';

export const REPO_LIST_CARD_DELETE_LOADING = 'REPO_LIST_CARD_DELETE_LOADING';
export const REPO_LIST_CARD_DELETE_LOADING_SUCCESS = 'REPO_LIST_CARD_DELETE_LOADING_SUCCESS';
export const REPO_LIST_CARD_DELETE_LOADING_FAILURE = 'REPO_LIST_CARD_DELETE_LOADING_FAILURE';

export const REPO_LIST_CARD_TITLE_UPDATE_REQUEST_LOADING = 'REPO_LIST_CARD_TITLE_UPDATE_REQUEST_LOADING';
export const REPO_LIST_CARD_TITLE_UPDATE_REQUEST_LOADING_SUCCESS = 'REPO_LIST_CARD_TITLE_UPDATE_REQUEST_LOADING_SUCCESS';
export const REPO_LIST_CARD_TITLE_UPDATE_REQUEST_LOADING_FAILURE = 'REPO_LIST_CARD_TITLE_UPDATE_REQUEST_LOADING_FAILURE';